markdown: rdiscount
permalink: /:title/
url: 
name: novakr
author: novakr
qq: 274212562
email: jr.zengjr@gmail.com
uyanid: 1982869
beian: 
cnzz: 
weibo: 1950056964
github: novakr
pygments: true
safe: true
paginate: 20
about: "这里是 novakr 的个人博客，创建于 2014 年 10 月。之前在 iteye,cnblog都写过 博客，2014 年 10 月开始正常玩github博客系统 Jekyll @ GitHub。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
